### ISSUE TITLE
Why the hard fork?

### ISSUE THREAD

**Issue by elsiehupp** [0xW1sKy/Stitch-For-Roku#27]
I looked at the Git commit history of this repository, and, yep, Stitch is a hard fork of Twoku!

But since Stitch is a hard fork of Twoku, I have to ask… why? Why not do a Pull Request, instead? It actually takes substantial effort to do a hard fork on GitHub (i.e. to sever a repository from an upstream fork), so… why?

(Oh, also: no, Amazon is not going to adopt a third-party Twitch client unless it is fully cleared by their legal department to have a permissive MIT/BSD-style license. As far as I can tell, neither Twoku nor Stitch has an explicit license, and getting any official adoption, or even just substantial third-party code contribution, is extremely unlikely unless that changes.)

**Comment by 0xW1sKy** [comment]
Their dev team doesn’t pay attention to their repo.

It’s not even current with their published version. I had PRs open for months without comment from them. When trying to reach out they told me more or less they’re not that interested in doing normal open source collaboration.

So I hard forked it and have been rewriting and optimizing since.

Now it’s almost a 100% rewrite. Still 1 or 2 bits of original code in the video player.
